### ISSUE TITLE
Написать ТЗ для проекта

### ISSUE THREAD

**Issue by hackfeed** [iu7og/bongodb#1]
Необходимо написать ТЗ проекта и формализовать требования. Обсуждаем в комментариях.

**Comment by TheSawIsTheLaw** [comment]
Обсуждаю в комментариях: авторами идеи являются @hackfeed, @CATFELLA  и @mRrvz, поэтому добавляю в assignees. В воскресенье уже нужно иметь техническое задание и направить его Евгению Борисовичу, редактуру могу предоставить от своего лица с обсуждением, поэтому требуется иметь сырую версию уже сегодня к вечеру.

**Comment by TheSawIsTheLaw** [comment]
Напоминаю о том, что ТЗ должно было быть вчера.

**Comment by hackfeed** [comment]
ТЗ будет оформлено сегодня.

**Comment by hackfeed** [comment]
Пока не ТЗ, но тоже важная часть документации: https://github.com/iu7og/bongodb/wiki/Регламенты-кодирования. Давайте обсудим здесь.

**Comment by TheSawIsTheLaw** [comment]
По доке (https://docs.google.com/document/d/1byr0Km2OSur4JpeWExoSR8N7gXB6mxlvjxw2rmu0x9g/edit?usp=sharing) не вижу никаких проблем, всё выглядит в данный момент хорошо и ничего не забыли. Единственное, поспорил бы о том, что не стоит писать тип переменной в её имени, но я просто люблю garnishDeliciousBelgianWaffleWithStrawberryList.

**Comment by hackfeed** [comment]
> но я просто люблю

Придется разлюбить :(

**Comment by mRrvz** [comment]
> Применять стиль кодирования, установленный используемым языком

в си++ кажется нет точного определения, писать camel кейсом или snake. у нас как будет?

**Comment by TheSawIsTheLaw** [comment]
> > Применять стиль кодирования, установленный используемым языком
> 
> в си++ кажется нет точного определения, писать camel кейсом или snake. у нас как будет?

Ставим лайк, если "за" самецЧехол

**Comment by TheSawIsTheLaw** [comment]
Так, а когда ТЗ всё-таки, если все регламенты уже на месте?

**Comment by hackfeed** [comment]
В процессе

**Comment by Justarone** [comment]
В общем, хочу внести свою лепту в обсуждение проекта и описать, как я его вижу на текущий момент с начальным разделением ответственности (то есть потом зоны ответственности могут поменяться, нужно просто с чего-то начать).

Обсуждение предлагаю разбить на 2 части:
1. близкая к ТЗ, описание основного функционала.
1.1. примерное разделение на компоненты.
1.2. назначение ответственных за компоненты.
3. детальное уточнение каждого компонента в рамках отдельных тикетов, по большей части в этом обсуждении уже будут участвовать отвественные, остальные будут наблюдателями с интересными идеями.

Сейчас предлагаю пройтись по п. 1.

Учитывая устные обсуждения, на текущий момент расклад примерно следующий:
* есть 4 человека, готовых писать на C++ - сама СУБД;
* есть 1 человек, готовый заняться инфраструктурой проекта.

### База данных

Минимальные требования:
1. Хранилище данных в формате ключ-значение (возможно, я неправильно понял, и в данных может быть какая-то схема, поправьте меня, если это так) в оперативной памяти, доступное на уровне объекта C++.
1.1. Поддержка следующих операций:
    * put набору значений
    * get по набору ключей
    * delete по набору ключей
2. Интерфейс (предварительно [gRPC](https://grpc.io/docs/languages/cpp/quickstart/), возможно HTTP REST вместо или вместе) для доступа на уровне отдельной программы.

Требования:
1. Возможность создания кластера с шардированием и репликацией. Задание параметров кластера с помощью конфигурационного файла.
1.1. Возможность выбора принципов шардирования (остаток от деления хэша ключа, отрезки значений ключа и тд).
1.2. Возможность выбора критерия успешности записи (кворум, все, хотя бы 1).
2. Оптимизации некоторых операций.
2.1. Партиционирование данных в рамках одного хранилища по признаку ключа (может быть значений, но в таком случае нужно знать схему данных).
3. Логирование и сбор метрик через известные системы (graphite, prometheus, logstash).

Возможно:
1. Возможность динамического обновления конфигурации:
1.1. Добавление реплик в процессе работы и инициализация состояния с уже имеющихся.
1.2. Перешардирование на большее количество шардов.
2. Возможность сохранения состояния на диске для потенциального восстановления:
2.1. Ведение журнала.
2.2. Создание snapshot'ов.
3. Возможность сохранения данных на диске для экономии места по некоторому критерию:
3.1. Хранение значений на диске, ключей в ОП.
3.2. Хранение части значений на диске исходя из: очередности записи | LRU | размера данных | комбинированного критерия и тд.
4. <Место для ваших предложений>

### Инфраструктура

Минимальные требования:
1. программа, упрощающая взаимодействие с интерфейсом БД (может быть CLI, WEB, GUI интерфейс для выполнения базовых операций БД)

Требования:
1. Монитор кластера:
1.1. Возможность перезапуска нод.
1.2. Возможность мониторинга состояния нод (сбор метрик, логов), шардов (обнаружение аномалий).

Возможно:
1. Реакция на аномалии, автоматическое перешардирование по критерию (разделение 1 шарда на 2, например).
2. <Место для ваших предложений>


Возможно это все выглядит сумбурно и не очень структурированно, но это уже что-то, что можно конструктивно обсудить. Очень хочу услышать ваши комментарии! @mRrvz @TheSawIsTheLaw @CATFELLA @hackfeed

**Comment by TheSawIsTheLaw** [comment]
Можно немного поподробнее о шардировании? В каком ключе это рассматривается? В качестве "кластера" что будем иметь?

**Comment by Justarone** [comment]
Кластер в данном контексте - множество нод (запущенных инстансов хранилища, предположительно на разных машинах, но не обязательно), для которых определен шард и реплика. Каждая нода знает о других репликах своего шарда.

Запись множества значений предположительно можно делать на любую ноду кластера, которая пошардирует (разобьет набор данных по критерию) и отправит разбитые наборы данных на нужные ноды.

Пример кластера с 2 репликами и 2 шардами:

Пусть 4 компьютера:
* Димин (1 шард, 1 реплика) - (1, 1)
* Пашин (1 шард, 2 реплика) - (1, 2)
* Сережин (2 шард, 1 реплика) - (2, 1)
* Мишин (2 шард, 2 реплика) - (2, 2)

Пусть есть мастер-мастер репликация.

Пусть шардируется все по остатку от деления ключа на количество шардов.

Тогда при записи набора значений [(1, "one"), (2, "two")] на ноду (2, 1) она:
* запишет [(1, "one")] у себя
* отправит запрос на запись [(1, "one")] ноде (2, 2)
* отправит запрос на запись нодам (1, 1), (1, 2) (или одной из них, а первая из них отправит второй, зависит от реализации)
* вернет клиенту некоторый ответ с успешностью записи

Если я не очень ответил на вопрос (или ответил не на тот), уточни, пожалуйста

**Comment by TheSawIsTheLaw** [comment]
Всё, понял. Выглядит как курсач по сетям просто из-за связи между инстантами. Задачка может раздуться, мне кажется, поэтому, может, это требование ещё подразбить на "возможное" и "требующееся"?

**Comment by Justarone** [comment]
Да, подразбить надо будет, но нужно еще уточнить, все ли согласны с текущим списком. Если да - то мы еще декомпозируем и синхронизируемся.

**Comment by mRrvz** [comment]
@Justarone +1

**Comment by Justarone** [comment]
Давайте соберём лайки на этом комментарии от всех и после этого перейдем к последующец декомпозиции и составлению ТЗ.

**Comment by Justarone** [comment]
Замечательно, этап №2.

Разделю на 2 комментария, чтобы можно было каждый отдельно обсудить:
1. по поводу тз
2. по поводу дальнейшей декомпозиции (следующий комментарий будет)

Выше я разбил требования в каждой части проекта на 3 группы, для каждого компонента планируется сделать 2, а 3 - если успеем и захотим. В связи с этим я полагаю, что в ТЗ нужно написать про первые 2 группы каждого компонента без уточнения деталей, чтобы было место для маневра в случае чего.

Первая версия ТЗ:
ТЕМА: __Распределенная in-memory СУБД__
ЗАДАНИЕ: __Разработать распределенную in-memory СУБД, хранящую данные в формате ключ-значение. СУБД должна поддерживать доступ к данным через HTTP API, позволять сохранять набор записей, получать и удалять записи по набору ключей, выбирать параметры кластера (такие как количество шардов, реплик, кворум). В состав СУБД должно входить ПО для работы с ней, а так же ПО для мониторинга ее состояния через централизованный сбор метрик и логов.__

Ставьте лайки или вопросы под этот комментарий, пишите замечания.

**Comment by TheSawIsTheLaw** [comment]
Мы не совсем готовы сказать точно, каков будет способ доступа к данным для пользователя, если я правильно помню. Предлагаю выразить эту часть более абстрактно, чтобы потом нельзя было докопаться до того, что мы, видите ли, вынуждены реализовывать что-то по ТЗ, хотя вспомнили о более простом/быстром/удобном решении. Если потом ЕБ нам скажет, что мы немного охренели, то поправим.
Таким образом фразу ```СУБД должна поддерживать доступ к данным через HTTP API``` я бы предложил заменить на ```СУБД должна предоставлять пользователю средство для сохранения набора...``` или что-то в этом роде.

**Comment by Justarone** [comment]
Мне кажется, что HTTP API дает нам много возможностей для маневра, потому что в него входят:
* REST API
* различные RPC
* какой-нибудь собственный топорный протокол
* whatever

просто есть предположение, что если мы хотим делать распределенное хранилище данных, то взаимодействия по сети на нам неизбежать. Учитывая, что городить свой супер протокол over TCP все равно будет менее эффективно (с учетом имеющихся у нас ресурсов), чем взять что-то уже работающее достаточно эффективно и надежно, скорее всего это будет что-то, работающее над HTTP. Когда мы обсуждали и не знали, хотим ли мы по сети или нет, то тогда мы еще не обсуждали распределенное хранилище. Поэтому я решил, что сейчас уже можно почти с уверенностью сказать, что мы будем работать по какой-то такой схеме. + при такой схеме достаточно просто будет писать клиентское приложение и другие примыкающие приложения.

**Comment by TheSawIsTheLaw** [comment]
Согласен полностью и бесповоротно, претензия снята

**Comment by Justarone** [comment]
Дальнейшая декомпозиция в #7

**Comment by Justarone** [comment]
По поводу styleguide может быть еще [такое](https://google.github.io/styleguide/cppguide.html#Naming) бы рассмотрел, кажется, достаточно уважаемый (там переменные в snake case, классы в camel и есть еще нюансы, но есть, на что ориентироваться)

**Comment by CATFELLA** [comment]
мне стайлгайд гугла нравится еще тем что можно просто clang-format на него накрутить

**Comment by CATFELLA** [comment]
тз написано? кто согласен ставим лайки

@hackfeed @CATFELLA @Justarone @mRrvz @TheSawIsTheLaw

**Comment by Justarone** [comment]
1. Описка в теме.
2. Я бы убрал "возможно" требования из требований, наверное, оставил бы набор поменьше (лучше сделать больше, чем заявляем, кажется)

**Comment by CATFELLA** [comment]
>     2. Я бы убрал "возможно" требования из требований, наверное, оставил бы набор поменьше (лучше сделать больше, чем заявляем, кажется)

а где там возможно?

**Comment by Justarone** [comment]
Ну я имею в виду, что я выше разделил требования на 3 категории: минимальные, просто требования и "возможно". Ты включил все требования в ТЗ, я бы убрал 3 часть требований.

**Comment by CATFELLA** [comment]
убрал

**Comment by Justarone** [comment]
Я бы ещё убрал перечисление известных систем

**Comment by Justarone** [comment]
Ну то есть просто указал бы, что импорт будет в одну из уже написанных систем сбора метрик/логов

**Comment by TheSawIsTheLaw** [comment]
> Ну то есть просто указал бы, что импорт будет в одну из уже написанных систем сбора метрик/логов

***"На усмотрение разработчика"***

**Comment by TheSawIsTheLaw** [comment]
Выглядит вкусно

**Comment by hackfeed** [comment]
Предлагаю закрыть тикет, так как основа у нас уже есть. Дальше по ходу будем добавлять в рамках других тикетов
