### ISSUE TITLE
Описать таблицу рисков проекта

### ISSUE THREAD

**Issue by TheSawIsTheLaw** [iu7og/bongodb#10]
В соответствии с новым "заданием" от "заказчика" от нас хотят видеть таблицу рисков. Описание колонок таблицы можно найти на странице 14 приложенного файла.

[Файлик делает "тык"](https://github.com/iu7og/bongodb/files/8148806/5.pdf)

На текущий момент требуется определить сами риски, заполнением таблицы могу заняться я.
Предлагаю каждому описать свои предложения в следующей форме:

* Формулировка риска;
* Стратегия (кратко, не более 15 слов), основываясь на существующих типах стратегии: уклонение, принятие, передача, снижение.

Касательно ответственных за риск можно будет либо найти того, кто готов отвечать за риск, либо обратиться к пресвятому ВБРу (что такое ВБР вам пояснит Лёша).

Прочие вещи уже будем согласовывать вместе по надобности.

**Comment by TheSawIsTheLaw** [comment]
Мои предложения на текущий момент:
---
**Тотальное разрушение ментального здоровья команды из-за ситуации в стране**

* Исключение депрессантов из списка потребление и уменьшение количества новостных каналов в подписках.
---
**Незавершение проекта по причине "мы делали лабы Курова"**
* Взаимодействие участников между собой, включающее поддержку и постоянные пинки.
---
**Отход одного из участников в мир иной**
* Переход дороги только в положенном месте, забота о собственном здоровье и соблюдение скоростного режима.
---
**Конфликт интересов в команде**
* Обсуждение идей в спокойной обстановке и работа в команде.
---
**Отсутствие анеков и мемов в иссюках**
* Добавление анеков и мемов в иссюки.

**Comment by Justarone** [comment]
лучше ВБР пояснить, конечно, потому что я нашел только что-то из :rainbow: ♂️ world of tanks ♂️ :rainbow: 

Для оценки рисков, нам нужно разобраться с тем, что мы делаем, поэтому данный тикет зависит от #1 и #7, кмк, потому что в нашем случае риск может возникнуть из-за неправильной оценки сложности задачи, компетенций и возможностей (под этим словом я в том числе подразумеваю время, которое человек готов тратить на проект, его загруженность по работе и тд) участников команды. Сложность задачи пока оценить не удалось.

В целом список выше норм, я бы еще добавил что-то, когда утвердим задачу.

**Comment by mRrvz** [comment]
> лучше ВБР пояснить, конечно, потому что я нашел только что-то из rainbow male_sign world of tanks male_sign rainbow

всё верно нашел

**Comment by TheSawIsTheLaw** [comment]
Добавлена первая ревизия таблицы рисков в [0b4ae2e](https://github.com/iu7og/bongodb/wiki/%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0-%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2/0b4ae2ee7b73becf1f32a16d734f5f305b02c65c).

Жду замечаний и несогласных. Также жду от вас предложений по тому, кто за какой риск отвечает на сегодняшний день

**Comment by hackfeed** [comment]
Беру риск "Конфликт интересов в команде"

**Comment by Justarone** [comment]
Отвечу за "мир иной".

**Comment by CATFELLA** [comment]
я не очень понимаю в чем ответственность человека на наших заключается, типа с рисками которые мы видели сегодня понятно что делает ответственный, а у нас? типа Паша ответит за "мир иной" как? воскресит?

и стратегия "Напоминания о личной ответственности каждого за своё здоровье", это же не решение риска, это стратегия предотвращения его происхождения

**Comment by TheSawIsTheLaw** [comment]
Ответственность Паши заключается в исполнении стратегии.

Второе замечание, на мой взгляд, верно, из слайдов понял не так. Значит, всё поправлю.

**Comment by TheSawIsTheLaw** [comment]
> я не очень понимаю в чем ответственность человека на наших заключается, типа с рисками которые мы видели сегодня понятно что делает ответственный, а у нас? типа Паша ответит за "мир иной" как? воскресит?
> 
> и стратегия "Напоминания о личной ответственности каждого за своё здоровье", это же не решение риска, это стратегия предотвращения его происхождения

Исправлено в  [d077a15](https://github.com/iu7og/bongodb/wiki/%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0-%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2/d077a153fbc8d1b897ef4741647df4da41d73f9b)

**Comment by hackfeed** [comment]
@TheSawIsTheLaw это отправлялось на ревью Россинскому?

**Comment by TheSawIsTheLaw** [comment]
> @TheSawIsTheLaw это отправлялось на ревью Россинскому?

На созвон уже этот вопрос выносим

**Comment by hackfeed** [comment]
@TheSawIsTheLaw не вынесли, надо отдать на ревью Россинскому

**Comment by hackfeed** [comment]
@TheSawIsTheLaw bump

**Comment by TheSawIsTheLaw** [comment]
@Justarone как тимлид, выбери двух жертв на два последних нераспределенных риска

**Comment by TheSawIsTheLaw** [comment]
Под данным комментом собираем пальцы вверх, если более рисков не добавляем

**Comment by TheSawIsTheLaw** [comment]
TODO: отказ от функционала при проблемах в команде

**Comment by TheSawIsTheLaw** [comment]
В [a3b62e4](https://github.com/iu7og/bongodb/wiki/%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0-%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2/a3b62e417650a5f77766d281324908298a743281) исправлены замечания по рискам. Также добавил риск недостижение заданного РПСа, привёл решение возникающих проблем по своим предположениям, если есть несогласные -- исправьте меня.

**Comment by TheSawIsTheLaw** [comment]
Сдано Евгению Борисовичу
