### ISSUE TITLE
Протестировать быстродействие контейнеров

### ISSUE THREAD

**Issue by Justarone** [iu7og/bongodb#13]
Контейнеры всякие:
* STL (unordered_map, map)
* google (sparse_hash_map, dense_hash_map)
* другие Open Source решения (можно посмотреть в Tarantool)
* свое решение (маловероятно)

Возможно стоит еще замерить память + важно учесть некоторые ограничения (в dense_hash_map в свое время нельзя было использовать не POD типы, важно уточнять такие моменты)

Чтобы закрыть задачу, нужно:

- [x]  Изучить другие проекты (Tarantool, redis)
- [x]  Собрать список контейнеров для тестирования
- [x] Посмотреть еще контейнеры, учесть новые два с открытой адресацией
- [x] Погуглить на предмет самых быстрых key-value структур данных, поискать всякие бенчмарки
- [x] Посмотреть тесты других проектов повнимательнее, может можно без труда спереть структуру и заиспользовать
- [x]  Протестировать на разных объемах и построить графики зависимости rps записи/чтения от текущего объема
- [ ]  [желательно] графики с занимаемой памятью

**Comment by TheSawIsTheLaw** [comment]
Из того, что я вижу, Tarantool и Redis используют свои структуры для создания контейнеров с нуля. Могу ошибаться, но изучать проект на 5 килотонн строк не имеет ни малейшего смысла.

Касательно контейнеров у меня дополнений нет.

Возникает вопрос касательно того, каким образом мы собираемся замерять rps. Предполагается, что мы хотим заполнить первоначально контейнер какими-то данными, а потом относительно каждой операции RUD посмотреть, сколько за секунду мы успеем сделать этих операций? Если так, то мне требуется точки ~факторного пространства~ по объёму данных.

**Comment by hackfeed** [comment]
Объем данных зависит от проекта, конечно, но в KV обычно супер большое что-то не хранят. Давайте, думаю, ориентироваться на 1GB, 2GB, 4GB

**Comment by Justarone** [comment]
> Из того, что я вижу, Tarantool и Redis используют свои структуры для создания контейнеров с нуля. Могу ошибаться, но изучать проект на 5 килотонн строк не имеет ни малейшего смысла.

Изучать _5 килотонн строк_ не нужно. Ты же не изучал столько же строк контейнеров из стандартной библиотеки. Нужно посмотреть, что используется (на уровне интерфейса посмотреть), поискать какие-нибудь статьи с бенчмарками этого дела, попробовать взять их c/cpp файлик, если это возможно (не говоря мгновенно, что это невозможно; я почти уверен, что можно модифицируя их unit-тесты провести нужные размеры) и провести замеры. Поискать еще решения, потому что большинство решений используют цепочки, а не открытую адресацию. [Вот](https://github.com/rigtorp/HashMap), например, нашлось какое-то решение с открытой адресацией, которое по словами челика гугол обгоняет. 

[Вот еще какое-то решение](https://probablydance.com/2018/05/28/a-new-fast-hash-table-in-response-to-googles-new-fast-hash-table/) (кстати там здоровские графики, похоже на то, что тебе нужно сделать: скорость вставки/чтения (можно еще память замерить) в зависимости от текущего размера контейнера (можно в байтах, можно в элементах)).

Дима, у тебя все получится, пожалуйста:
* возьми в расчет те 2 СД, что я скинул выше
* посмотри еще раз, как контейнеры в Redis и Tarantool **используются**, на уровне интерфейса (посмотри хотя бы, там деревья или хэш таблицы, открытая адресация или цепочки, и вот это все)
* посмотри, может быть какая-нибудь структура данных thread-safe и позволит из коробки писать из разных потоков и будет делать это эффективнее других со средствами синхронизации

Ответ на вопрос: предполагается, что ты N раз возьмешь контейнер и будешь замерять на каждых M элементах время. значением для i-ой отметки будет `1 / Ti` (то есть при M = 1000 и T1 = 3.33 секунды (время, за которое записано 1000 элементов)). График хочу [какой-то вот такой](https://probablydance.files.wordpress.com/2018/05/bytell_successful.png?w=650), только от обратной величины, наверное. 

rps чтения можно проверять на каждой итерации после записи: записал M элементов -> прочитал рандомные M элементов (сущетсвующих и не существующих).

Верю, что ты можешь, пожалуйста!

**Comment by TheSawIsTheLaw** [comment]
@Justarone той ли дорогой мы идем, товарищ?

![ффф](https://user-images.githubusercontent.com/55848738/159552306-592d217d-ae18-4696-8cd1-dec4c3637e51.png)

**Comment by TheSawIsTheLaw** [comment]
> Замечательно, той! Один из нужных вариантов! Можешь код залить и ссылку на ветку приложить, пожалуйста?

Сделаем

**Comment by TheSawIsTheLaw** [comment]
@Justarone получите и распишитесь https://github.com/iu7og/bongodb/tree/feature/GH-13

**Comment by hackfeed** [comment]
@TheSawIsTheLaw а где PR?

**Comment by TheSawIsTheLaw** [comment]
![Я приду, когда зацветёт весна, и окрасит в розовый собой облака, соберу букет полевых цветов и спрячу, и мое сердечко болит от любви, просто слушай, ничего мне не говори, первое свидание последней весны, я плачу](https://user-images.githubusercontent.com/55848738/160215109-50746d89-cff7-4b52-9f23-105316c23e16.png)
@Justarone

**Comment by TheSawIsTheLaw** [comment]
@Justarone 
![assshit](https://user-images.githubusercontent.com/55848738/160215412-0ae877b2-065d-47df-bf97-6fc09cdea1dd.png)

**Comment by Justarone** [comment]
Жму руку, то, что нужно. Давай сделаем то же самое на других контейнерах.

**Comment by Justarone** [comment]
[Выглядит здорово](https://github.com/abseil/abseil-cpp), случайно узнал, смотря лекцию по распределенным системам... Нужно протестировать...

**Comment by TheSawIsTheLaw** [comment]
> [Выглядит здорово](https://github.com/abseil/abseil-cpp), случайно узнал, смотря лекцию по распределенным системам... Нужно протестировать...

Не хватает конкретики, из Quick Start понятно примерно, что это не расширение std.

**Comment by Justarone** [comment]
Я [вот про что](https://abseil.io/docs/cpp/guides/container)

**Comment by TheSawIsTheLaw** [comment]
@Justarone (svg, поэтому тыкай и рассматривай)
![zzz](https://user-images.githubusercontent.com/55848738/160287314-d5343a2a-e998-41b6-ac61-a31aa3a6dcf8.svg)

**Comment by TheSawIsTheLaw** [comment]
Если кому-то будет интересно
[Файл с резами в Calc](https://github.com/iu7og/bongodb/files/8357891/results.ods)

**Comment by TheSawIsTheLaw** [comment]
[robin_map](https://github.com/Tessil/robin-map)

**Comment by hackfeed** [comment]
А почему получаются такие крутые пики? Это какой-то баг в замерах или что?

**Comment by hackfeed** [comment]
robin-map выглядит как сын маминой подруги, но меня немного напрягает, что v1.0.0 зарелижен 2 дня назад

**Comment by TheSawIsTheLaw** [comment]
> А почему получаются такие крутые пики? Это какой-то баг в замерах или что?

Судя вот по этому [тык на бенчи](https://tessil.github.io/2016/08/29/benchmark-hopscotch-map.html), мы не знаем, что это такое, но если бы мы знали, что это такое, но мы не знаем, что это такое

**Comment by hackfeed** [comment]
Бенчмарки огонь! Думаю можно было даже свои не делать, а взять эту ссылку за основу. Выглядит так, будто реально надо брать robin_map, если мы хотим супер флекс быстрое решение
