### ISSUE TITLE
Протестировать быстродействие ноды

### ISSUE THREAD

**Issue by Justarone** [iu7og/bongodb#14]
Желательно использовать для тестов взаимодействие по gRPC сразу.

Что нужно:

- [x]  написать сервер-обработчик http (grpc/rest) запросов get/put операций (ничего не делает, только парсит ключи/значения и лепит ответ, ничего не кладет никуда).
- [x]  написать клиента, который будет синхронно (то есть поочередно, дожидаясь завершения запроса) и асинхронно (то есть отправлять очередной запрос не дожидаясь завершения предыдущего) дергать по http сервер (можно использовать готовые решения, если есть на примете).
- [ ] привести rps для работы с одной нодой для разных способов работы.
- [ ]  [желательно] замерить профиль, в котором будет понятно, сколько времени занимает передача по сети (в рамках одного хоста) и парсинг

**Comment by mRrvz** [comment]
собрал вот этот grps [key-value storage](https://github.com/grpc/grpc/tree/master/examples/cpp/keyvaluestore) - выдаёт в среднем 4500~ rps

**Comment by mRrvz** [comment]
```bash
$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           113
Model name:                      AMD Ryzen 7 3700X 8-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         3032.502
CPU max MHz:                     4426.1709
CPU min MHz:                     2200.0000
BogoMIPS:                        7186.82
Virtualization:                  AMD-V
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        32 MiB
```

**Comment by Justarone** [comment]
Выглядит очень здорово (результат медленноватый, но тест отличный)! Давай еще в несколько потоков с клиента нападем на сервер + надо бы погуглить, как работает grpc сервер (есть ли асинхронщина из коробки или надо будет самим крутить).

**Comment by mRrvz** [comment]
На асинхронном сервере выдается около 16-20 тысыяч rps (один поток)
