### ISSUE TITLE
Уточнить схему репликации и шардирования

### ISSUE THREAD

**Issue by Justarone** [iu7og/bongodb#15]
Для закрытия ишью нужно ответить на следующие вопросы:

- [x]  какая репликация будет использоваться и почему (master-master, master-slave и тд)?
- [x]  будет ли перешардирование и если будет, то как будет работать?
- [x]  как ведет себя реплика при выпадении (потери подключения к другим)? как ведут себя другие реплики?

**Comment by Justarone** [comment]
# Репликация

## Виды

В [некоторых источниках](https://habr.com/ru/post/514500/) репликацию делят на 3 вида:
* блочная (на уровне диска, raid-массивы и подобные технологии)
* физическая (на уровне субд)
* логическая (на уровне клиента: создается детерминированный запрос и на уровне апи вызывается у всех нужных реплик)

В рамках данного проекта планируется реализовать физическую репликацию. Блочную репликацию можно организовать при развертывании, логическая репликация, возможно, будет сделана на уровне клиентского приложения.

## Виды физической репликации

Физическая репликация имеет свою классификацию, как минимум, по 2 признакам:
* синхронность
    * асинхронные - работают быстрее, но в произвольный момент времени состояние реплик может быть несогласованным
    * синхронные - данные согласованы, но решение менее производительно
* равнозначность
    * мастер-мастер репликация. Все реплики равнозначны, на все можно писать и со всех можно читать.
    * мастер-слейв репликация. запись производиться только на мастер реплику, чтение доступно со всех реплик.

## CAP-теорема

(по-простому можно почитать [тут](https://habr.com/ru/post/130577/))
Для распределенных систем существует CAP-теорема, которая гласит о том, что для распределенной системы можно соблюсти только 2 свойства из 3:
* C - consistency - согласованность. В любой момент времени состояние реплик согласовано и результат обращения к СУБД не зависит от выбора реплики.
* A - availability - если хотя бы одна реплика доступна, то она работает и отвечает на запросы.
* P - partition tolerance - если теряется связь между репликами, то каждая реплика по отельности функционирует **ожидаемо** (*)

(*) имеется в виду, что если происходит разделение кластера на составные части, то при необходимости наличия согласованности части кластера становятся недоступными (до момента восстановления кластера), либо выдают несогласованные данные (при необходимости доступности.

Так вот насчет соблюдения 2 свойств, что можно получить (вот [тут](https://stackoverflow.com/questions/36404765/why-isnt-rdbms-partition-tolerant-in-cap-theorem-and-why-is-it-available) замечательно написано):
* CA - Consistency + Availability - нет защиты от партиционирования. В случае master-slave репликации это может работать следующим образом: слейвы, отключившиеся от мастера, перестают отвечать на запросы (ждут доступности мастера).
* AP - Availability + partition tolerance - нет согласованности. В некоторый момент времени состояние слейвов может отставать, например, но при этом они все еще будут отдавать ответы на запросы, однако ответы реплик могут отличаться.
* CP - Consistency + Partition tolerance - нет доступности. Такие кластеры работают таким образом, что при партиционировании кластера отделенная часть (неспособная поддерживать согласованность) становится недоступной для запросов, при этом согласованная часть продолжает функционировать.

Вопрос для самопроверки: чем отличается CP от CA? (ответ в конце этого комментария)

## Шардирование

Существует много разных схем по шардированию данных, приведу несколько примеров:
1. Ручное шардирование. Так работает движок [ReplicatedMergeTree](https://clickhouse.com/docs/ru/engines/table-engines/mergetree-family/replication/) в ClickHouse, то есть фактически шардирование происходит на уровне клиента. Такой подход очень эффективен, потому что данные приходят сразу на реплику, принадлежащую нужному шарду, и нет ситуации, когда приходится пересылать данные на другой шард. Однако такой подход может быть неудобен, поэтому придумали еще 1 решение.
2. Автоматическое шардирование по выражению. Чаще всего в качестве выражения используется отстаток от деления составной части ключа на количество шардов (таким образом выбирается нужный шард). В том же ClickHouse это можно сделать с помощью таблицы на [Distrubuted](https://clickhouse.com/docs/ru/engines/table-engines/special/distributed/) движке поверх кластера из ReplicatedMergeTree таблиц. Подобным образом происходит шардирование в СУБД [Bob](https://github.com/qoollo/bob)
2.1. Автоматическое шардирование по диапазонам с возможностью перешардирования. Данный подход используется, например, в облачной базе Яндекса [YDB](https://cloud.yandex.ru/docs/ydb/best_practices/schema_design) (это [один из вариантов](https://cloud.yandex.ru/docs/ydb/best_practices/table_sharding); строго говоря там речь о партиционировании, но запись в один диапазон нагружает один сервер, поэтому этот термин схож с термином шардирования) и его преимущество заключается в том, что при достижении какого-то лимита по объему/нагрузки данные партиции делятся на 2 и для перешардирования требуется перевезти только половину данных 1 шарда (страшно представить перешардирование в системе, работающей с остатком от деления)

## Схемы репликаций в существующих проектах

To be continued

**Comment by Justarone** [comment]
Планирую изучить 2 документа: [репликация в Redis](https://redis.io/topics/replication) + [репликация в MySQL]
@CATFELLA попробуй погуглить что-нибудь на эту тему тоже. Слышал, что в Tarantool используется multi-paxos алгоритм (то есть они писали свой алгоритм достижения консенсуса и вот это все.. видимо, это для master-master схемы и обеспечения consistency и транзакционности, мы можем на это подзабить, я думаю, потому что в том же redis'e асинхронная схема по умолчанию (хотя можно включить синхронную, но они пишут, что она все равно не обеспечивает полную consistency))

**Comment by hackfeed** [comment]
Bump. 11 дней назад последние телодвижения, непорядок
