### ISSUE TITLE
Настроить CI/CD для запуска сборки, тестов, линтера проекта

### ISSUE THREAD

**Issue by hackfeed** [iu7og/bongodb#26]
Необходимо настроить полный CI/CD цикл:

- Сборка после пуша

- Запуск тестов после пуша

- Запуск линтера после пуша

- Отведение релиза путем создания тега, ченджлога

**Comment by TheSawIsTheLaw** [comment]
В #46 теперь доступен запуск отдельно тестовой сборки и самого сервера через (в папке кора):

```Shell
cmake .
make bongo
make test
```

Билдятся бинарники bongo и test соответственно

**Comment by TheSawIsTheLaw** [comment]
Линтер пофикшен в https://github.com/iu7og/bongodb/pull/55
