### ISSUE TITLE
Оформить документацию для `bongodb`

### ISSUE THREAD

**Issue by hackfeed** [iu7og/bongodb#27]
Необходимо своевременно документировать core-код для последующей генерации [(про генерацию)](https://developer.lsst.io/cpp/api-docs.html) документации.

**Comment by TheSawIsTheLaw** [comment]
Вопрос на грумминг: выделяем это как таску, которая будет In progress до первого релиза проекта, или закроем её, выдав требование того, что все документируют в данном стиле?
Если первый вариант, то появится ряд просьб к написанию свежих кусков кода просто

**Comment by TheSawIsTheLaw** [comment]
@hackfeed пилипопенгую

**Comment by hackfeed** [comment]
Что ты подразумеваешь под груммингом?

**Comment by TheSawIsTheLaw** [comment]
> Что ты подразумеваешь под груммингом?

Причёсывание бэклога. Я вижу, что таска может быть подразбита на несколько более мелких тасок, остаться такой же большой, либо же вообще не быть таской

**Comment by hackfeed** [comment]
Нужно документировать код по мере его написания, а не судорожно писать после релиза. Поэтому просто обсуждаем тут соглашения о документации, принимаем решение и закрываем таску

**Comment by TheSawIsTheLaw** [comment]
Предлагаю использовать стиль доксика. Обязательо комментим начало файла. В аннотациях к методам -- обязательно описываем ретурны и параметры. Для классов -- бриф и в детейлах назначение + особенности.

https://habr.com/ru/post/252101/

**Comment by TheSawIsTheLaw** [comment]
В ветке feature/GH-27 добавлены темплейты для комментов, которые потребуется заполнить

**Comment by TheSawIsTheLaw** [comment]
@mRrvz  на бренче представлены примеры того, как всё должно быть закомменчено. Паша в петке feature/GH-37 оставит мини-комментарии, которые надо будет перенести в соответствии с стилем доксигена

**Comment by TheSawIsTheLaw** [comment]
@mRrvz обновление, в мастере для Backend.h лежит пример, его надо будет ещё дозаполнить, 27-ю ветку сейчас удаляю, пересоздашь
