### ISSUE TITLE
Добавить лейблов для issue в проект

### ISSUE THREAD

**Issue by hackfeed** [iu7og/bongodb#6]
Необходимо добавить осмысленных лейблов и удалить ненужные

**Comment by TheSawIsTheLaw** [comment]
Давайте здесь каждый выскажет своё мнение по поводу, что нужно убрать, а что добавить.

**Comment by TheSawIsTheLaw** [comment]
Я бы убрал лишь "good first issue" и попросил бы объяснений к тому, что такое "panfrost". Остальное seems legit

**Comment by hackfeed** [comment]
Не вижу смысла в лейблах `panfrost`, `in design` (можно заменить просто на `design`, у нас на доске есть статусы задач), `question` (можно спросить в чате), `help wanted` (аналогично), `invalid` (тот же самый `wontfix`). Кроме того не вижу смысла добавлять (если кому-то захочется) приоритеты для багов, потому как на доске багтрекера тоже это есть. Думаю стоит добавить лейблы по типу `core` (для задач системного уровня) и `app` (для клиентских задач). Так можно будет сортировать доску чтобы видеть только свои задачи.

**Comment by CATFELLA** [comment]
все правильно, но invalid и wontfix разные, в первом случае ишью некорректное (такой ситуации нет, или написано неправильно), а во втором случае просто лень фиксить/нет денег/религия не позволяет

**Comment by TheSawIsTheLaw** [comment]
Поддержу @hackfeed, но при этом ```help wanted``` всё-таки лучше оставить, чтобы можно было нормально сохранить историю решения тех или иных вопросов, а не носиться потом по всему чату в поисках, где же ты там этот вопрос задал и получил ответ через день-два.

**Comment by TheSawIsTheLaw** [comment]
Студент четвёртый курс не знать слака. Студент не нравится, что он не ответить тебе на этот вопрос...

**Comment by mRrvz** [comment]
ящитаю "good first issue" должно быть

**Comment by CATFELLA** [comment]
но это вообще говоря лейбл для опенсорс проектов чтобы помечать простые задачи для молодых

**Comment by mRrvz** [comment]
у нас опенсорс проект, и молодые тоже присутствуют

**Comment by Justarone** [comment]
Я бы добавил тогда, когда он понадобится

**Comment by hackfeed** [comment]
Давайте тогда остановимся на финальном списке:
```
bug
documentation
duplicate
enhancement
help wanted
invalid
wontfix
+design
+app
+core
```
